export type CatalogTask = {
  id: string;
  taskType?: "goal" | "subtask" | "operational";
  parentGoalId?: string | null;
  sortOrder?: number;
  title: string;
  category: string;
  priority: "Kritik" | "Yüksek" | "Orta" | "Düşük";
  status: "Başlamadı" | "Devam Ediyor" | "Beklemede" | "Onay Bekliyor" | "Tamamlandı" | "İptal Edildi";
  dueDate?: string | null;
  owner: string;
  nextAction: string;
  decision?: string;
  followUpDate?: string | null;
  managementAgenda: boolean;
  risk?: string;
};

export const additionalTasks: CatalogTask[] = [
  {
    id: "boran-tatbikati",
    title: "BORAN VIII Uluslararası Keskin Nişancı Yarışması katılımı",
    category: "Etkinlik ve Protokol",
    priority: "Kritik",
    status: "Devam Ediyor",
    owner: "Sait Bakırcı / Tatbikat Ekibi",
    nextAction: "Günlük programı, saha iletişim ihtiyaçlarını, görsel kayıtları ve yönetim katılım akışını tek planda kesinleştir.",
    decision: "Tatbikat süresince iletişim ve temsil öncelikleri",
    followUpDate: "2026-09-10",
    managementAgenda: true,
    risk: "Saha programındaki anlık değişiklikler içerik, protokol ve görsel kayıt akışını etkileyebilir.",
  },
  {
    id: "boran-atis-planlama",
    taskType: "subtask",
    parentGoalId: "boran-tatbikati",
    sortOrder: 10,
    title: "Keskin nişancı atışlarının planlanması",
    category: "Yarışma Operasyonu",
    priority: "Kritik",
    status: "Devam Ediyor",
    owner: "Sait Bakırcı / Yarışma Ekibi / Teknik Ekip",
    nextAction: "Atış senaryolarını, antrenman akışını, saha saatlerini ve teknik ihtiyaçları kesinleştir.",
    decision: "Atış planı ve saha görev dağılımı",
    followUpDate: "2026-09-10",
    managementAgenda: false,
    risk: "Saha programındaki değişiklikler antrenman ve yarışma hazırlığını etkileyebilir.",
  },
  {
    id: "boran-urun-secimi",
    taskType: "subtask",
    parentGoalId: "boran-tatbikati",
    sortOrder: 20,
    title: "Yarışmaya götürülecek ürünlerin belirlenmesi",
    category: "Ürün ve Teknik Hazırlık",
    priority: "Kritik",
    status: "Devam Ediyor",
    owner: "Sait Bakırcı / Teknik Birimler / Lojistik",
    nextAction: "Götürülecek sistem, aksesuar, yedek parça ve tanıtım materyali listesini teknik birimlerle kapat.",
    decision: "Nihai ürün ve ekipman listesi",
    followUpDate: "2026-09-10",
    managementAgenda: false,
    risk: "Eksik teknik ekipman saha kabiliyetini ve ürün sunumunu doğrudan etkiler.",
  },
  {
    id: "boran-ulasim-sevkiyat",
    taskType: "subtask",
    parentGoalId: "boran-tatbikati",
    sortOrder: 30,
    title: "Ulaşım ve ürün sevkiyatının planlanması",
    category: "Lojistik",
    priority: "Yüksek",
    status: "Devam Ediyor",
    owner: "Sait Bakırcı / Lojistik / Yarışma Ekibi",
    nextAction: "Personel ulaşımını, araç planını, ürün sevk-teslim saatlerini ve sorumluları tek akışta kesinleştir.",
    decision: "Araç, sevkiyat ve teslim planı",
    followUpDate: "2026-09-10",
    managementAgenda: false,
    risk: "Personel ve ürün hareketleri ayrı planlanırsa saha giriş ve teslim süreçleri aksayabilir.",
  },
  {
    id: "boran-konaklama",
    taskType: "subtask",
    parentGoalId: "boran-tatbikati",
    sortOrder: 40,
    title: "Konaklama planının tamamlanması",
    category: "Organizasyon",
    priority: "Yüksek",
    status: "Devam Ediyor",
    owner: "Sait Bakırcı / İdari İşler / Yarışma Ekibi",
    nextAction: "Katılımcı listesini konaklama günleri, oda dağılımı ve ulaşım saatleriyle eşleştir.",
    decision: "Konaklama listesi ve rezervasyon teyidi",
    followUpDate: "2026-09-10",
    managementAgenda: false,
    risk: "Katılımcı veya tarih değişiklikleri rezervasyon ve maliyet planını etkileyebilir.",
  },
  {
    id: "boran-ekip-gorev-dagilimi",
    taskType: "subtask",
    parentGoalId: "boran-tatbikati",
    sortOrder: 50,
    title: "Katılımcı ekip ve görev dağılımı",
    category: "Organizasyon ve Koordinasyon",
    priority: "Yüksek",
    status: "Devam Ediyor",
    owner: "Sait Bakırcı / Yönetim / Yarışma Ekibi",
    nextAction: "Katılımcıları, saha sorumlularını, teknik desteği ve iletişim görevlerini isim bazında netleştir.",
    decision: "Nihai katılımcı listesi ve görev matrisi",
    followUpDate: "2026-09-10",
    managementAgenda: false,
    risk: "Sorumluluklar isim bazında kapanmazsa saha koordinasyonu kişilere bağlı ve dağınık ilerler.",
  },
  {
    id: "urge-konya",
    title: "UR-GE Projesi – üye kazanımı ve kurumsal ziyaretler",
    category: "İş Geliştirme",
    priority: "Kritik",
    status: "Beklemede",
    owner: "Sait Bakırcı / Konya Sanayi Odası",
    nextAction: "Mevcut 10 üyeyi teyit et; hedef şirket listesini çıkararak Konya Sanayi Odası ile kurumsal ziyaret takvimi oluştur.",
    decision: "Ziyaret programı, sorumlular ve üyelik hedefi",
    followUpDate: "2026-09-16",
    managementAgenda: true,
    risk: "Yeni kurumsal ziyaretler başlatılmazsa proje mevcut 10 üyede kalabilir ve ilerleme sağlayamaz.",
  },
  {
    id: "idef-2027-yerlesim-stand",
    title: "IDEF 2027 yerleşim planı ve ortak stant tasarımı",
    category: "Fuar ve Etkinlik",
    priority: "Yüksek",
    status: "Devam Ediyor",
    owner: "Sait Bakırcı / ASELSAN Sivas / İlgili Birimler",
    nextAction: "Yerleşim alternatiflerini netleştir; ASELSAN Sivas ile ortak stant ihtiyaç ve tasarım brifini oluştur.",
    decision: "Yer seçimi, ortak kullanım modeli ve tasarım yaklaşımı",
    followUpDate: "2026-09-16",
    managementAgenda: true,
    risk: "Yerleşim kararı gecikirse tasarım, bütçe ve üretim takvimi sıkışabilir.",
  },
  {
    id: "2027-hediye-butcesi",
    title: "2027 promosyon ve kurumsal hediye bütçesi",
    category: "Bütçe ve Planlama",
    priority: "Yüksek",
    status: "Devam Ediyor",
    owner: "Sait Bakırcı / Satın Alma / Mali İşler",
    nextAction: "Çalışan hediyeleri, kurumsal hediyeler ve promosyon ürünlerini adet, birim maliyet ve kullanım amacıyla bütçe tablosuna bağla.",
    decision: "2027 bütçe limiti ve ürün grubu öncelikleri",
    followUpDate: "2026-09-16",
    managementAgenda: true,
    risk: "Adet ve ürün segmentasyonu yapılmadan bütçe gerçekçi oluşmaz.",
  },
  {
    id: "urun-anahtarliklari",
    title: "MAKS 40, SMASH ve SARP ürün anahtarlıkları",
    category: "Promosyon ve Kurumsal Hediye",
    priority: "Orta",
    status: "Devam Ediyor",
    owner: "Sait Bakırcı / Tasarım / Tedarikçi",
    nextAction: "Üç ürün için model, malzeme, ölçü, renk ve numune onaylarını tamamlayarak üretim takvimini teyit et.",
    decision: "Numune ve üretim onayı",
    followUpDate: "2026-09-15",
    managementAgenda: false,
    risk: "Ürün geometrisinin küçük ölçekte okunabilirliği ve marka detaylarının üretilebilirliği doğrulanmalı.",
  },
  {
    id: "urun-maketleri",
    title: "SMASH, NEFER, SARP ve MAKS 40 ürün maketleri",
    category: "Ürün İletişimi",
    priority: "Yüksek",
    status: "Devam Ediyor",
    dueDate: "2026-09-30",
    owner: "Sait Bakırcı / Maket Üreticisi / Teknik Birimler",
    nextAction: "Üretim ilerlemesini ve teknik doğruluğu kontrol et; eylül teslimi öncesi ara kontrol ve kabul planını oluştur.",
    decision: "Nihai teknik ve görsel kabul",
    followUpDate: "2026-09-15",
    managementAgenda: false,
    risk: "Teknik detay hataları veya geç numune kontrolü eylül teslimini riske atabilir.",
  },
  {
    id: "engineerhub-2027-baslangic",
    title: "EngineerHub 2027 programının başlatılması",
    category: "Eğitim ve Yetenek",
    priority: "Kritik",
    status: "Devam Ediyor",
    dueDate: "2026-10-31",
    owner: "Sait Bakırcı / EngineerHub Paydaşları",
    nextAction: "Program kapsamını, takvimi, katılımcıları ve görev dağılımını kesinleştir; ekim ayındaki açılış programını planla.",
    decision: "2027 program modeli, açılış tarihi ve kaynak planı",
    followUpDate: "2026-09-15",
    managementAgenda: true,
    risk: "Açılış takvimi ve sorumlular erken netleşmezse katılımcı ve paydaş koordinasyonu gecikebilir.",
  },
  {
    id: "engineerhub-buyuksehir",
    title: "EngineerHub – Konya Büyükşehir Belediyesi değerlendirme ve bütçe görüşmesi",
    category: "Paydaş Yönetimi",
    priority: "Yüksek",
    status: "Başlamadı",
    owner: "Sait Bakırcı / Konya Büyükşehir Belediyesi",
    nextAction: "Programın çıktılarını ve 2027 ihtiyaçlarını sunan görüşme dosyasını hazırlayarak değerlendirme toplantısı talep et.",
    decision: "Belediye katkısı ve talep edilecek bütçe kalemleri",
    followUpDate: "2026-09-18",
    managementAgenda: true,
    risk: "Bütçe talebi ölçülebilir çıktı ve net maliyet kalemleriyle desteklenmezse karar süreci uzayabilir.",
  },
  {
    id: "teknofest-organizasyon",
    title: "TEKNOFEST katılımı ve yönetim organizasyonu",
    category: "Fuar ve Etkinlik",
    priority: "Kritik",
    status: "Devam Ediyor",
    owner: "Sait Bakırcı / Yönetim / İlgili Birimler",
    nextAction: "Kurumsal katılım kapsamını, yönetim programını, akreditasyonları, ulaşım-konaklama ve yaka kartı ihtiyaçlarını kesinleştir.",
    decision: "Katılımcı listesi ve yönetim programı",
    followUpDate: "2026-09-11",
    managementAgenda: true,
    risk: "Katılımcı ve akreditasyon bilgilerinin geç tamamlanması organizasyonu aksatabilir.",
  },
  {
    id: "mtal-yurt",
    title: "Aselsan Konya MTAL yurt süreci",
    category: "Eğitim Altyapısı",
    priority: "Yüksek",
    status: "Beklemede",
    owner: "Sait Bakırcı / MEB / İl Millî Eğitim Müdürlüğü",
    nextAction: "Mevcut aşamayı, bekleyen resmî işlemleri, sorumluları ve karar tarihini yazılı takip planına bağla.",
    decision: "Yurt modelinin ve uygulama takviminin netleştirilmesi",
    followUpDate: "2026-09-16",
    managementAgenda: true,
    risk: "Kurumlar arası görev ve takvim netleşmezse süreç belirsiz süreyle bekleyebilir.",
  },
  {
    id: "mtal-yetenek-kesfi-baslangic",
    title: "Aselsan Konya MTAL Yetenek Keşfi programının başlatılması",
    category: "Eğitim ve Yetenek",
    priority: "Yüksek",
    status: "Başlamadı",
    owner: "Sait Bakırcı / Okul Yönetimi / Teknik Değerlendiriciler",
    nextAction: "Program takvimini hazırla; 9. ve 10. sınıflara konu ve kriterleri ilet, 11. sınıfların geçen yılki çalışmalarını inceleyip raporla.",
    decision: "Konu setleri, değerlendirme kriterleri ve uygulama takvimi",
    followUpDate: "2026-09-15",
    managementAgenda: false,
    risk: "Sınıf bazında beklentiler ayrıştırılmazsa değerlendirme standardı bozulabilir.",
  },
  {
    id: "mtal-yetenek-kesfi-ziyaret-sunum",
    title: "Yetenek Keşfi yeni öğrenci tesis ziyareti ve sınıf sunumları",
    category: "Eğitim ve Etkinlik",
    priority: "Yüksek",
    status: "Başlamadı",
    owner: "Sait Bakırcı / Okul Yönetimi / Tesis Birimleri",
    nextAction: "Yeni öğrencilerin tesis ziyaretini ve 9. ile 11. sınıfların konferans salonu sunumlarını tek günlük akışta planla; öğrenci sunumlarını önceden incele.",
    decision: "Ziyaret tarihi, sunum sırası ve tesis içi görev dağılımı",
    followUpDate: "2026-09-18",
    managementAgenda: false,
    risk: "Sunum ön incelemesi, güvenlik ve saha akışı aynı takvimde koordine edilmelidir.",
  },
  {
    id: "mtal-pyk",
    title: "Aselsan Konya MTAL PYK toplantısı",
    category: "Eğitim Yönetişimi",
    priority: "Yüksek",
    status: "Başlamadı",
    owner: "Sait Bakırcı / PYK Üyeleri / Okul Yönetimi",
    nextAction: "Gündem maddelerini, katılımcıları, karar gerektiren konuları ve toplantı tarih alternatiflerini oluştur.",
    decision: "Toplantı tarihi ve gündem onayı",
    followUpDate: "2026-09-18",
    managementAgenda: true,
    risk: "Karar maddeleri önceden olgunlaştırılmazsa toplantı bilgilendirme düzeyinde kalabilir.",
  },
  {
    id: "mtal-ogrenci-soylesi",
    title: "Aselsan Konya MTAL öğrencileriyle söyleşi",
    category: "Eğitim ve Etkinlik",
    priority: "Orta",
    status: "Başlamadı",
    owner: "Sait Bakırcı / Konuşmacılar / Okul Yönetimi",
    nextAction: "Söyleşi temasını, konuşmacıyı, öğrenci grubunu ve tarih alternatiflerini belirle.",
    decision: "Konuşmacı ve program tarihi",
    followUpDate: "2026-09-21",
    managementAgenda: false,
    risk: "Amaç ve hedef öğrenci grubu belirlenmeden etkinlik etkisi ölçülemez.",
  },
  {
    id: "mtal-meb-yatirimlari",
    title: "Aselsan Konya MTAL MEB yatırımlarının planlanması",
    category: "Eğitim Altyapısı",
    priority: "Yüksek",
    status: "Başlamadı",
    owner: "Sait Bakırcı / MEB / Okul Yönetimi",
    nextAction: "Okulun öncelikli yatırım ihtiyaçlarını etki, maliyet ve aciliyet bazında sıralayarak MEB görüşme dosyasını hazırla.",
    decision: "2026–2027 yatırım öncelikleri ve finansman modeli",
    followUpDate: "2026-09-21",
    managementAgenda: true,
    risk: "İhtiyaçlar teknik gerekçe ve yaklaşık maliyetle desteklenmezse bütçe sürecine giremeyebilir.",
  },
  {
    id: "mtal-il-mem-kitaplari",
    title: "Aselsan Konya MTAL binasındaki İl Millî Eğitim kitaplarının kaldırılması",
    category: "Eğitim Altyapısı",
    priority: "Orta",
    status: "Beklemede",
    owner: "Sait Bakırcı / İl Millî Eğitim Müdürlüğü / Okul Yönetimi",
    nextAction: "Kitapların envanter ve sahiplik durumunu teyit ederek resmî yazışma, taşıma sorumlusu ve kaldırma tarihini netleştir.",
    decision: "Teslim/taşıma yöntemi ve tarih",
    followUpDate: "2026-09-16",
    managementAgenda: false,
    risk: "Resmî devir ve taşıma sorumluluğu belirlenmeden fiziksel işlem yapılmamalıdır.",
  },
  {
    id: "mtal-egitim-yili-acilis",
    title: "Aselsan Konya MTAL yeni eğitim yılı açılış programı",
    category: "Eğitim ve Protokol",
    priority: "Yüksek",
    status: "Başlamadı",
    owner: "Sait Bakırcı / Yönetim / Okul Yönetimi",
    nextAction: "Program tarihini, kurumsal temsil düzeyini, konuşma ihtiyacını ve ziyaret akışını teyit et.",
    decision: "Yönetim katılımı ve protokol seviyesi",
    followUpDate: "2026-09-11",
    managementAgenda: true,
    risk: "Davet ve yönetim takvimi geç netleşirse temsil planı aksayabilir.",
  },
  {
    id: "mtal-temrinlik",
    title: "Aselsan Konya MTAL temrinlik ödeneklerinin takibi",
    category: "Eğitim ve Bütçe",
    priority: "Yüksek",
    status: "Devam Ediyor",
    owner: "Sait Bakırcı / Mali İşler / Okul Yönetimi",
    nextAction: "Ödenek tutarı, ödeme adımı, gerekli belge ve okul hesabına aktarım takvimini netleştir.",
    decision: "Ödeme onayı ve aktarım tarihi",
    followUpDate: "2026-09-16",
    managementAgenda: true,
    risk: "Belge veya onay eksikliği okulun eğitim materyali tedarikini geciktirebilir.",
  },
  {
    id: "mtal-burs-2026-2027",
    title: "Aselsan Konya MTAL yeni dönem burs planlaması",
    category: "Eğitim ve Sosyal Etki",
    priority: "Yüksek",
    status: "Başlamadı",
    owner: "Sait Bakırcı / İK / Okul Yönetimi",
    nextAction: "25 öğrenci için başarı kriterleri, seçim takvimi, ödeme yöntemi ve iletişim sürecini oluştur.",
    decision: "Burs kriterleri, tutarı ve ödeme takvimi",
    followUpDate: "2026-09-21",
    managementAgenda: true,
    risk: "Kriter ve sorumluluklar açık tanımlanmazsa seçim ve itiraz süreci oluşabilir.",
  },
  {
    id: "mtal-etkinlik-programi",
    title: "Aselsan Konya MTAL öğrenci etkileşim programı",
    category: "Eğitim ve Sosyal Etki",
    priority: "Orta",
    status: "Başlamadı",
    owner: "Sait Bakırcı / İlgili Birimler / Okul Yönetimi",
    nextAction: "Öğrenci geri bildirimlerini temalara ayırarak Aselsan Konya'da söyleşi, eğitim ve teknik ziyaretlerden oluşan yıllık etkinlik planı hazırla.",
    decision: "Yıllık etkinlik sayısı, içerik sahipleri ve kaynak planı",
    followUpDate: "2026-09-25",
    managementAgenda: false,
    risk: "Etkinlikler tekil taleplerle yürütülürse süreklilik ve ölçülebilir etki oluşmaz.",
  },
  {
    id: "yilsonu-kidem",
    title: "Aselsan Konya yıl sonu etkinliği ve kıdem hediyeleri",
    category: "İç İletişim ve Etkinlik",
    priority: "Yüksek",
    status: "Başlamadı",
    dueDate: "2026-12-31",
    owner: "Sait Bakırcı / İK / Satın Alma",
    nextAction: "Etkinlik konseptini, kıdem hak sahiplerini, hediye seçeneklerini, bütçeyi ve üretim takvimini planla.",
    decision: "Konsept, bütçe ve kıdem hediyesi seçimi",
    followUpDate: "2026-09-25",
    managementAgenda: true,
    risk: "Hak sahibi listesi ve ürün tedariki geç kalırsa yıl sonu teslimi riske girer.",
  },
  {
    id: "yeniyil-hediye-tedarik",
    title: "2027 yılbaşı hediyelerinin satın alınması ve dağıtımı",
    category: "İç İletişim ve Satın Alma",
    priority: "Yüksek",
    status: "Başlamadı",
    dueDate: "2026-12-15",
    owner: "Sait Bakırcı / İK / Satın Alma",
    nextAction: "Çalışan anketi sonuçlandıktan sonra adetleri kesinleştir; satın alma, teslim kontrolü ve dağıtım planını başlat.",
    decision: "Nihai adetler, sipariş ve dağıtım takvimi",
    followUpDate: "2026-09-14",
    managementAgenda: false,
    risk: "Anket sonucu ile sipariş takvimi arasında gecikme olursa ürünler yılbaşına yetişmeyebilir.",
  },
  {
    id: "ssb-2027-milli-katilim-fuarlar",
    title: "SSB 2027 Millî Katılım destekli yurt dışı fuarları",
    category: "Uluslararası Fuarlar",
    priority: "Kritik",
    status: "Beklemede",
    owner: "Sait Bakırcı / İş Geliştirme ve Pazarlama / SSB",
    nextAction: "SSB'nin 2027 Millî Katılım fuar takvimini takip et; açıklanan fuarları hedef pazar, ürün, maliyet ve yönetim katılımı açısından önceliklendir.",
    decision: "Katılım sağlanacak fuarlar ve yıllık uluslararası etkinlik bütçesi",
    followUpDate: "2026-09-30",
    managementAgenda: true,
    risk: "Resmî takvim açıklanmadan kesin başvuru ve bütçe kararı verilemez; duyurular düzenli izlenmelidir.",
  },
  {
    id: "ssb-insan-yonetimi-baslangic",
    title: "Savunma Sanayii İnsan Yönetimi Olgunluk Modeli başlangıç toplantısı",
    category: "Etkinlik ve Protokol",
    priority: "Kritik",
    status: "Devam Ediyor",
    dueDate: "2026-09-16",
    owner: "Sait Bakırcı / İK / Teknik ve Protokol Ekipleri",
    nextAction: "Heyet programını, konferans salonu akışını, karşılama-protokol detaylarını ve kurumsal iletişim içeriklerini kapat.",
    decision: "Nihai program ve yönetim katılım akışı",
    followUpDate: "2026-09-11",
    managementAgenda: true,
    risk: "Program, sahne yönetimi ve protokol akışı tek koordinasyon planında birleştirilmelidir.",
  },
  {
    id: "bilim-festivali-2026",
    title: "Konya Bilim Festivali 2026 katılımı",
    category: "Tamamlanan Fuar ve Etkinlik",
    priority: "Yüksek",
    status: "Tamamlandı",
    dueDate: "2026-08-23",
    owner: "Sait Bakırcı / Etkinlik Ekibi",
    nextAction: "Etkinlik arşivi, ziyaretçi çıktıları ve kapanış kayıtları tamamlandı.",
    decision: "Tamamlandı",
    followUpDate: null,
    managementAgenda: false,
    risk: "",
  },
  {
    id: "sarper-isimlendirme-raporu",
    title: "SARPER ürün ailesi stratejik isimlendirme ön analiz raporu",
    category: "Tamamlanan Ürün ve Marka",
    priority: "Yüksek",
    status: "Tamamlandı",
    dueDate: "2026-08-31",
    owner: "Sait Bakırcı",
    nextAction: "Ön analiz ve rakip değerlendirmesi tamamlandı; karar süreci KUBAD isimlendirme kaydında sürüyor.",
    decision: "Rapor tamamlandı",
    followUpDate: null,
    managementAgenda: false,
    risk: "",
  },
  {
    id: "mtal-yetenek-2025-2026-faz2",
    title: "Aselsan Konya MTAL Yetenek Keşfi 2025–2026 Faz 2",
    category: "Tamamlanan Eğitim ve Yetenek",
    priority: "Orta",
    status: "Tamamlandı",
    dueDate: "2026-08-31",
    owner: "Sait Bakırcı / Okul Yönetimi / Değerlendiriciler",
    nextAction: "Faz 2 tamamlandı; yeni dönem çalışmaları ayrı proje kaydında izleniyor.",
    decision: "Tamamlandı",
    followUpDate: null,
    managementAgenda: false,
    risk: "",
  },
  {
    id: "sahaexpo-2026",
    title: "SAHA EXPO 2026 katılımı",
    category: "Tamamlanan Fuar ve Etkinlik",
    priority: "Orta",
    status: "Tamamlandı",
    dueDate: "2026-05-09",
    owner: "Sait Bakırcı / Fuar Ekibi",
    nextAction: "Katılım tamamlandı; düşük ziyaretçi trafiği sonraki etkinlik seçimleri için değerlendirme notu olarak kaydedildi.",
    decision: "Tamamlandı",
    followUpDate: null,
    managementAgenda: false,
    risk: "",
  },
  {
    id: "wds-2026",
    title: "World Defense Show 2026 katılımı",
    category: "Tamamlanan Uluslararası Fuar",
    priority: "Yüksek",
    status: "Tamamlandı",
    dueDate: "2026-02-24",
    owner: "Sait Bakırcı / İş Geliştirme ve Pazarlama",
    nextAction: "MAKS 40'ın ilk uluslararası gösterimi tamamlandı; sonuçlar gelecek fuar planlarına girdi oluşturuyor.",
    decision: "Tamamlandı",
    followUpDate: null,
    managementAgenda: false,
    risk: "",
  },
  {
    id: "mtal-mezuniyet-2026",
    title: "Aselsan Konya MTAL 2026 mezuniyet programı",
    category: "Tamamlanan Eğitim ve Etkinlik",
    priority: "Orta",
    status: "Tamamlandı",
    dueDate: "2026-07-23",
    owner: "Sait Bakırcı / Okul Yönetimi",
    nextAction: "54 öğrencinin mezuniyet programı ve başarı dağılımı raporlaması tamamlandı.",
    decision: "Tamamlandı",
    followUpDate: null,
    managementAgenda: false,
    risk: "",
  },
  {
    id: "iskur-iep-protokol",
    title: "İŞKUR İşbaşı Eğitim Programı protokol iletişimi",
    category: "Tamamlanan Kurumsal İletişim",
    priority: "Yüksek",
    status: "Tamamlandı",
    dueDate: "2026-09-02",
    owner: "Sait Bakırcı / İŞKUR Konya / Yönetim",
    nextAction: "Protokol programı, konuşma ve basın iletişimi çalışmaları tamamlandı.",
    decision: "Tamamlandı",
    followUpDate: null,
    managementAgenda: false,
    risk: "",
  },
  {
    id: "elmas-mtal-eslestirme",
    title: "ELMAS Programı kapsamında MTAL ilişkilendirmesi",
    category: "İptal Edilen Eğitim Çalışması",
    priority: "Düşük",
    status: "İptal Edildi",
    dueDate: "2026-09-02",
    owner: "Sait Bakırcı / Yönetim",
    nextAction: "Program Aselsan Konya MTAL'yi kapsamadığı için ilişkilendirme metinlerden çıkarıldı; ayrı aksiyon bulunmuyor.",
    decision: "Kapsam dışı olduğu için iptal edildi",
    followUpDate: null,
    managementAgenda: false,
    risk: "Yeniden gündeme alınacaksa SSB kapsam teyidi gerekir.",
  },
];
