export type MemoryKind = "İlerleme" | "Karar" | "Yöntem" | "Plan" | "Doküman" | "Toplantı Notu";

export type MemorySeed = {
  id: string;
  taskId: string;
  kind: MemoryKind;
  title: string;
  detail: string;
  eventDate: string;
  documentName?: string;
  documentVersion?: string;
  documentUrl?: string;
  isCurrent?: boolean;
  source?: "Görüşme" | "Geçmiş çalışma" | "Sistem";
  sourceRef?: string;
};

export const memoryCatalog: MemorySeed[] = [
  {
    id: "mem-kubad-final-three",
    taskId: "kubad-isimlendirme",
    kind: "Karar",
    title: "Üç final isim adayı netleştirildi",
    detail: "KUBAD ana aday; YONERK birinci rezerv, NOVRION ikinci rezerv olarak yönetim değerlendirmesine taşındı.",
    eventDate: "2026-09-08",
    source: "Görüşme",
  },
  {
    id: "mem-kubad-two-stage",
    taskId: "kubad-isimlendirme",
    kind: "Yöntem",
    title: "İki aşamalı onay modeli kuruldu",
    detail: "İcra Kurulu stratejik isim sırasını onaylayacak; nihai kullanım marka, hedef dil, hedef ülke ve dijital doğrulama sonrasında kesinleşecek.",
    eventDate: "2026-09-08",
    source: "Geçmiş çalışma",
  },
  {
    id: "mem-kubad-report-v2",
    taskId: "kubad-isimlendirme",
    kind: "Doküman",
    title: "Yönetim karar dosyası hazırlandı",
    detail: "KUBAD'ın tarihsel dayanağı, ürünle ilişkisi, aday sıralaması, marka mimarisi ve yönetimden beklenen karar ayrıntılandırıldı.",
    eventDate: "2026-09-08",
    documentName: "SARPER_Urun_Ailesi_Stratejik_Isimlendirme_Raporu (3).pdf",
    documentVersion: "Karar için - Sürüm 2.0",
    isCurrent: true,
    source: "Geçmiş çalışma",
  },
  {
    id: "mem-kubad-report-v1",
    taskId: "kubad-isimlendirme",
    kind: "Doküman",
    title: "İlk değerlendirme raporu arşivlendi",
    detail: "Üç adayın anlam ve stratejik rotalarını açıklayan ilk sürüm. Güncel karar dosyasının önceki versiyonudur.",
    eventDate: "2026-09-08",
    documentName: "SARPER_Urun_Ailesi_Stratejik_Isimlendirme_Raporu (2).pdf",
    documentVersion: "İlk değerlendirme sürümü",
    isCurrent: false,
    source: "Geçmiş çalışma",
  },
  {
    id: "mem-kubad-explanation",
    taskId: "kubad-isimlendirme",
    kind: "İlerleme",
    title: "KUBAD anlatımı yönetim diliyle geliştirildi",
    detail: "İkinci dokümanın KUBAD'ın tarihsel dayanağını, marka hikâyesini ve ürünle stratejik ilişkisini ayrıntılandıran geliştirilmiş karar versiyonu olduğu netleştirildi.",
    eventDate: "2026-09-09",
    source: "Görüşme",
  },
  {
    id: "mem-sarper-analysis",
    taskId: "sarper-isimlendirme-raporu",
    kind: "Yöntem",
    title: "İsimlendirme öncesi analiz tamamlandı",
    detail: "SARP'tan kalıcı ayrışma, hafiflik, küçük silüet, erişilebilir UKSS konumu ve gelecekteki yapay zekâ kabiliyetleri temel değerlendirme eksenleri olarak kullanıldı.",
    eventDate: "2026-08-31",
    source: "Geçmiş çalışma",
  },
  {
    id: "mem-sarper-report",
    taskId: "sarper-isimlendirme-raporu",
    kind: "Doküman",
    title: "Ön analiz raporu tamamlandı",
    detail: "Yurt içi ve yurt dışı rakipler, Afrika pazarı, fiyat-performans konumu ve marka mimarisi karar öncesi çerçevede birleştirildi.",
    eventDate: "2026-08-31",
    documentName: "Marka Mimarisi ve İsimlendirme Öncesi Analiz Raporu",
    documentVersion: "Onaylanan son sürüm",
    isCurrent: true,
    source: "Geçmiş çalışma",
  },
  {
    id: "mem-kubad-mockup",
    taskId: "kubad-mockup",
    kind: "İlerleme",
    title: "KUBAD ürün üzeri uygulaması hazırlandı",
    detail: "Marka adı silah sistemi gövdesi üzerinde mock-up olarak uygulanarak görsel okunurluk ve ürünle uyum açısından değerlendirildi.",
    eventDate: "2026-09-07",
    source: "Görüşme",
  },
  {
    id: "mem-maks40-latest",
    taskId: "maks40-sunum",
    kind: "Doküman",
    title: "Güncel Türkçe sunum esas sürüm olarak belirlendi",
    detail: "İngilizce içerik çalışmasının en son güncellenen Türkçe dosya üzerinden ilerlemesi; mevcut İngilizce görsellerin korunması kararlaştırıldı.",
    eventDate: "2026-09-04",
    documentName: "MAKS40_Sunum_TR(2).pptx",
    documentVersion: "Güncel Türkçe içerik sürümü",
    isCurrent: true,
    source: "Görüşme",
  },
  {
    id: "mem-maks40-translation",
    taskId: "maks40-sunum",
    kind: "Karar",
    title: "İngilizce sunum kapsamı netleştirildi",
    detail: "Kurum tanıtım slaytlarını Sait Bakırcı ayrıca ekleyecek; çalışma yalnızca ürün içeriklerinin İngilizceye çevrilmesine odaklanacak.",
    eventDate: "2026-09-04",
    source: "Görüşme",
  },
  {
    id: "mem-foca-plan",
    taskId: "foca-cekim",
    kind: "İlerleme",
    title: "AKONS ve MAKS 40 saha çekimleri planlandı",
    detail: "7-10 Eylül 2026 tarihleri için Foça çekim takvimi oluşturuldu; görüntü kontrolü ve kurgu planı takip adımı olarak bırakıldı.",
    eventDate: "2026-09-07",
    source: "Geçmiş çalışma",
  },
  {
    id: "mem-gift-survey-content",
    taskId: "yilbasi-hediye",
    kind: "İlerleme",
    title: "Duyuru ve anket içeriği hazırlandı",
    detail: "Arçelik filtre kahve makinesi, Arçelik dikey süpürge, Samsonite sırt çantası, Samsonite kabin boy valiz ve American Tourister orta boy valiz seçenekleri duyuru yapısına işlendi.",
    eventDate: "2026-09-09",
    source: "Görüşme",
  },
  {
    id: "mem-gift-survey-decision",
    taskId: "yilbasi-hediye",
    kind: "Karar",
    title: "Anket sorumluluğu ve kapanış tarihi belirlendi",
    detail: "Talep toplama İK sorumluluğunda ilerleyecek. Çalışan seçimlerinin 11 Eylül 2026 Cuma saat 17.00'ye kadar tamamlanması ve dağıtım için ayrıca bilgilendirme yapılması kararlaştırıldı.",
    eventDate: "2026-09-09",
    source: "Görüşme",
  },
  {
    id: "mem-vmix-request",
    taskId: "heyet-vmix",
    kind: "Doküman",
    title: "vMix hazırlık talebi oluşturuldu",
    detail: "16 Eylül heyet programı için lisans, sahne yönetimi, ses-görüntü sürekliliği ve teknik prova ihtiyacını içeren İlker Bey'e gönderilecek e-posta hazırlandı.",
    eventDate: "2026-09-09",
    documentName: "16 Eylül Heyet Programı - vMix Hazırlık Talebi",
    documentVersion: "Gönderime hazır metin",
    isCurrent: true,
    source: "Görüşme",
  },
  {
    id: "mem-boran-current",
    taskId: "boran-tatbikati",
    kind: "İlerleme",
    title: "Katılım süreci aktif saha gündemine alındı",
    detail: "Yarışma katılımının atış planı, ürün seçimi, ulaşım-sevkiyat, konaklama, ekip-görev dağılımı ve iletişim materyalleri olarak ayrı iş paketleriyle yönetilmesine karar verildi.",
    eventDate: "2026-09-10",
    source: "Görüşme",
  },
  {
    id: "mem-boran-patch-decisions",
    taskId: "boran-patch",
    kind: "İlerleme",
    title: "Patch tasarım yönü netleştirildi",
    detail: "AKONS çıkarıldı; BORAN, Türk bayrağı, International Sniper Competition ve ortalanmış beyaz 2026 kullanımı benimsendi. TPU üretim, Aselsan Konya laciverti, sade çizgiler ve ürünün öne çıkması esas alındı.",
    eventDate: "2026-09-02",
    source: "Geçmiş çalışma",
  },
  {
    id: "mem-urge-status",
    taskId: "urge-konya",
    kind: "İlerleme",
    title: "Üye sayısı 10'a ulaştı",
    detail: "Konya Sanayi Odası ile yürütülen UR-GE projesinde 10 üyeye ulaşıldı; yeni katılım olmadığı için süreç ilerlemiyor.",
    eventDate: "2026-09-09",
    source: "Görüşme",
  },
  {
    id: "mem-urge-next-method",
    taskId: "urge-konya",
    kind: "Plan",
    title: "Kurumsal ziyaret yöntemi benimsendi",
    detail: "Hedef şirket listesi çıkarılarak Konya Sanayi Odası ile birlikte yüz yüze kurumsal ziyaret takvimi oluşturulacak.",
    eventDate: "2026-09-09",
    source: "Görüşme",
  },
  {
    id: "mem-idef-joint-stand",
    taskId: "idef-2027-yerlesim-stand",
    kind: "Karar",
    title: "Ortak stant çalışma modeli belirlendi",
    detail: "IDEF 2027 yerleşim süreciyle birlikte stant tasarımının ASELSAN Sivas ile koordineli yürütülmesi kararlaştırıldı.",
    eventDate: "2026-09-09",
    source: "Görüşme",
  },
  {
    id: "mem-gift-budget-scope",
    taskId: "2027-hediye-butcesi",
    kind: "Karar",
    title: "2027 hediye bütçesinin kapsamı genişletildi",
    detail: "Bütçenin çalışan yılbaşı hediyeleriyle sınırlı kalmaması; kurumsal hediyeler ve promosyon ürünlerini de içermesi kararlaştırıldı.",
    eventDate: "2026-09-09",
    source: "Görüşme",
  },
  {
    id: "mem-keychains-products",
    taskId: "urun-anahtarliklari",
    kind: "İlerleme",
    title: "Anahtarlık ürün seti belirlendi",
    detail: "MAKS 40, SMASH ve SARP ürünlerine ait anahtarlıkların yaptırılması için çalışma başlatıldı.",
    eventDate: "2026-09-09",
    source: "Görüşme",
  },
  {
    id: "mem-models-delivery",
    taskId: "urun-maketleri",
    kind: "İlerleme",
    title: "Ürün maketleri üretime alındı",
    detail: "SMASH, NEFER, SARP ve MAKS 40 maketlerinin üretimi devam ediyor; teslim hedefi Eylül 2026 olarak takip ediliyor.",
    eventDate: "2026-09-09",
    source: "Görüşme",
  },
  {
    id: "mem-engineerhub-start",
    taskId: "engineerhub-2027-baslangic",
    kind: "Plan",
    title: "2027 program başlangıç çerçevesi oluşturuldu",
    detail: "Programın başlatılması, sürecin izlenmesi ve açılış programının Ekim 2026 içinde yapılması hedeflendi.",
    eventDate: "2026-09-09",
    source: "Görüşme",
  },
  {
    id: "mem-engineerhub-budget",
    taskId: "engineerhub-buyuksehir",
    kind: "Plan",
    title: "Büyükşehir bütçe görüşmesi gündeme alındı",
    detail: "EngineerHub çıktılarının Konya Büyükşehir Belediyesi ile değerlendirilmesi ve 2027 için gerekli bütçelerin talep edilmesi planlandı.",
    eventDate: "2026-09-09",
    source: "Görüşme",
  },
  {
    id: "mem-teknofest-scope",
    taskId: "teknofest-organizasyon",
    kind: "Plan",
    title: "Katılım ve yönetim organizasyonu kapsamı belirlendi",
    detail: "Yönetim katılımı, ulaşım-konaklama, akreditasyon, yaka kartı ve saha programının tek organizasyon akışında izlenmesi planlandı.",
    eventDate: "2026-09-09",
    source: "Görüşme",
  },
  {
    id: "mem-talent-phase2",
    taskId: "mtal-yetenek-2025-2026-faz2",
    kind: "İlerleme",
    title: "Yetenek Keşfi Faz 2 tamamlandı",
    detail: "9. ve 10. sınıflar için literatür ve proje değerlendirmesi tamamlandı. Baraj 85; özgünlük, kaynak, görsel, anlatım, yapay zekâ beyanı, motivasyon ve sunum kriterleri kullanıldı.",
    eventDate: "2026-08-31",
    source: "Geçmiş çalışma",
  },
  {
    id: "mem-talent-new-cycle",
    taskId: "mtal-yetenek-kesfi-baslangic",
    kind: "Plan",
    title: "Yeni dönem sınıf bazlı çalışma modeli tanımlandı",
    detail: "9. ve 10. sınıflara konu setleri verilecek; 11. sınıfların geçen yılki çalışmaları incelenerek raporlanacak. Yeni yılda öğrenci sunumları yapılacak.",
    eventDate: "2026-09-09",
    source: "Görüşme",
  },
  {
    id: "mem-talent-visit",
    taskId: "mtal-yetenek-kesfi-ziyaret-sunum",
    kind: "Plan",
    title: "Tesis ziyareti ve sunum günü tek akışta kurgulandı",
    detail: "Yeni öğrencilerin tesis ziyaretiyle 9. ve 11. sınıf sunumlarının konferans salonunda aynı gün yapılması; sunumların önceden incelenmesi planlandı.",
    eventDate: "2026-09-09",
    source: "Görüşme",
  },
  {
    id: "mem-mtal-burs",
    taskId: "mtal-burs-2026-2027",
    kind: "Karar",
    title: "Burs kapsamı 25 öğrenci olarak belirlendi",
    detail: "MEB-Aselsan Konya MTAL protokolü kapsamında eğitim-öğretim yılı içinde başarılı 25 öğrenciye her yıl burs verilmesi planlandı.",
    eventDate: "2026-08-31",
    source: "Geçmiş çalışma",
  },
  {
    id: "mem-ga4-method",
    taskId: "ga4-raporu",
    kind: "Yöntem",
    title: "GA4 yönetim raporu yöntemi oluşturuldu",
    detail: "1, 3 ve 6 aylık ülke verileri hedef pazar ve rakip bağlamında tek raporda birleştirildi; yaş, cinsiyet ve ilgi alanı verilerindeki eşik ve temsil sınırlılıklarının açıkça belirtilmesi benimsendi.",
    eventDate: "2026-08-26",
    source: "Geçmiş çalışma",
  },
  {
    id: "mem-ga4-report",
    taskId: "ga4-raporu",
    kind: "Doküman",
    title: "Stratejik trafik raporu hazırlandı",
    detail: "Google Analytics verileri, G2G ve B2G hedef pazar yaklaşımıyla üst yönetim raporuna dönüştürüldü.",
    eventDate: "2026-08-26",
    documentName: "ASELSAN_Konya_GA4_Stratejik_Trafik_Raporu_2026_Final.docx",
    documentVersion: "Final",
    isCurrent: true,
    source: "Geçmiş çalışma",
  },
  {
    id: "mem-magazine-direction",
    taskId: "hepimiz-bir",
    kind: "Karar",
    title: "Dergi adı ve kurumsal dil yönü netleştirildi",
    detail: "Dergi adı Hepimiz 1 olarak belirlendi; 3832.NEWS ibaresinin kaldırılması ve tüm içeriklerin kurum kültürüne göre yeniden düzenlenmesi istendi.",
    eventDate: "2026-09-02",
    source: "Görüşme",
  },
  {
    id: "mem-agenda-messages",
    taskId: "ajanda-mesajlari",
    kind: "Doküman",
    title: "Personel ve paydaş mesajları hazırlandı",
    detail: "Üretim gücü, Konya ekosistemi ve 2027 öncelikleri öne çıkarılarak personel ve paydaş mesajları; Genel Müdür'e e-posta ve kısa WhatsApp sunum metni hazırlandı.",
    eventDate: "2026-08-31",
    documentName: "2027 Ajanda Personel ve Paydaş Mesajları",
    documentVersion: "Yönetim onayına sunulan sürüm",
    isCurrent: true,
    source: "Geçmiş çalışma",
  },
  {
    id: "mem-science-festival",
    taskId: "bilim-festivali-2026",
    kind: "İlerleme",
    title: "Konya Bilim Festivali katılımı tamamlandı",
    detail: "50-75 m² stant, 85 inç ekran ve ses sistemiyle katılım sağlandı. İçişleri Bakanı Mustafa Çiftçi'nin stand ziyareti gerçekleştirildi ve MAKS 40 maketi takdim edildi.",
    eventDate: "2026-08-23",
    source: "Geçmiş çalışma",
  },
  {
    id: "mem-sahaexpo-method",
    taskId: "sahaexpo-2026",
    kind: "Yöntem",
    title: "Fuar değerlendirme yöntemi kayıt altına alındı",
    detail: "Düşük ziyaretçi trafiği sonraki etkinlik seçimlerinde dikkate alınacak. Fiziksel sınırların netleştirilmesi, şirket bazlı bağımsız tahsis, profesyonel şoförlü araç ve kapasite kotası önerileri oluşturuldu.",
    eventDate: "2026-05-09",
    source: "Geçmiş çalışma",
  },
  {
    id: "mem-sahaexpo-report",
    taskId: "sahaexpo-2026",
    kind: "Doküman",
    title: "Fuar değerlendirme raporu tamamlandı",
    detail: "Katılım, trafik, organizasyon ve sonraki etkinliklere aktarılacak yöntemler raporlandı.",
    eventDate: "2026-05-09",
    documentName: "SAHA EXPO 2026 FUAR DEĞERLENDİRMESİ V1.docx",
    documentVersion: "V1",
    isCurrent: true,
    source: "Geçmiş çalışma",
  },
  {
    id: "mem-wds",
    taskId: "wds-2026",
    kind: "İlerleme",
    title: "MAKS 40'ın ilk uluslararası gösterimi tamamlandı",
    detail: "MAKS 40, Riyad'daki World Defense Show 2026 kapsamında ilk kez uluslararası ziyaretçilere sunuldu.",
    eventDate: "2026-02-24",
    source: "Geçmiş çalışma",
  },
  {
    id: "mem-graduation",
    taskId: "mtal-mezuniyet-2026",
    kind: "İlerleme",
    title: "54 öğrencinin mezuniyet programı tamamlandı",
    detail: "Mezunların ilk 1.000, 10.000, 20.000, 50.000 ve 100.000 başarı dilimlerindeki dağılımı raporlandı.",
    eventDate: "2026-07-23",
    source: "Geçmiş çalışma",
  },
  {
    id: "mem-iskur-decisions",
    taskId: "iskur-iep-protokol",
    kind: "Karar",
    title: "Protokol iletişim çerçevesi kesinleştirildi",
    detail: "12 kişi ifadesi ve MTAL vurgusu çıkarıldı. SSB yalnızca atıf olarak bırakıldı; ELMAS kapsamı kullanılmadı. Millî Yetkinlik Hamlesi hedefleriyle örtüşme ifadesi benimsendi.",
    eventDate: "2026-09-02",
    source: "Geçmiş çalışma",
  },
  {
    id: "mem-elmas-cancelled",
    taskId: "elmas-mtal-eslestirme",
    kind: "Karar",
    title: "ELMAS-MTAL ilişkilendirmesi kapsam dışı bırakıldı",
    detail: "Genel Müdür değerlendirmesiyle ELMAS Programı'nın Aselsan Konya MTAL'yi kapsamadığı netleşti; ilgili bağlantı içeriklerden çıkarıldı.",
    eventDate: "2026-09-02",
    source: "Görüşme",
  },
  {
    id: "mem-web-last-checks",
    taskId: "web-yayin",
    kind: "Plan",
    title: "Yayın öncesi son kontrol kapsamı belirlendi",
    detail: "İngilizce içeriklerin son kontrolü, Aselsan Konya Özel ibaresinin yerleşimi ve sayfa bazlı yayın öncesi kontroller takip listesine alındı.",
    eventDate: "2026-09-09",
    source: "Görüşme",
  },
  {
    id: "mem-ssb-fairs",
    taskId: "ssb-2027-milli-katilim-fuarlar",
    kind: "Plan",
    title: "2027 millî katılım fuarları takip modeli oluşturuldu",
    detail: "SSB fuar takvimi, katılım kararı, başvuru, bütçe, stant-lojistik ve yönetim katılımı ayrı alt adımlarla izlenecek.",
    eventDate: "2026-09-09",
    source: "Görüşme",
  },
  {
    id: "mem-ssb-hr-program",
    taskId: "ssb-insan-yonetimi-baslangic",
    kind: "İlerleme",
    title: "Başlangıç toplantısı iletişim çalışmaları tamamlandı",
    detail: "Heyet karşılama, program içeriği, konferans salonu akışı, kurumsal paylaşım metni ve teknik ihtiyaçlar birlikte ele alındı.",
    eventDate: "2026-09-09",
    source: "Görüşme",
  },
];
